#!/bin/bash

NAME="superlists"                               # Name of the application
SERVER="dev.lerouge.info"
DJANGODIR=/var/www/packageManager/superlists             # Django project directory
SOCKFILE=/var/gunicorn/$SERVER  # we will communicte using this unix socket
USER=doctori                                        # the user to run as
GROUP=doctori                                     # the group to run as
NUM_WORKERS=4                                     # how many worker processes should Gunicorn spawn
DJANGO_WSGI_MODULE=superlists.wsgi                     # WSGI module nameœ
echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../virtualenv/bin/activate
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../virtualenv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --error-logfile=/var/log/gunicorn/error-$NAME.log\
  --access-logfile=/var/log/gunicorn/acces-$NAME.log

